name: Smoke tests

on:
  push:
    branches:
      - master

jobs:
  test-all-together-with-latest-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 12.0.2

      - name: Install all the tools together
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest
          lein: latest

      - name: Execute dummy clojure code
        run: lein run -m luminusdiff.core
